### ISSUE TITLE
Was it normal not to be able to run out of all epochs?

### ISSUE THREAD

**Issue by k-user** [awslabs/gluon-ts#1103]
Like this：

![image](https://user-images.githubusercontent.com/42017849/96853599-22b28080-148d-11eb-9a70-992772693fa5.png)
This happens every time run Epochs around 200.

Another question:
When i set num_workers,Errors occur
`OMP: Error #13: Assertion failure at z_Linux_util.cpp(2338).`

Maybe causes cuda initialization error  #1054 
Because add `KMP_INIT_AT_FORK=FALSE` to run my code , cuda initialization error.
Like this:
`KMP_INIT_AT_FORK=FALSE /home/usr/anaconda3/bin/python3.7 -u /home/usr/main_train.py`
Return:
`AssertionError: Something went wrong with the worker initialization.`

**Comment by lostella** [comment]
Hey @k-user yes, this is due to learning rate reduction and early stopping logic in the provided `Trainer` class. You can find documentation to the related options here: https://gluon-ts.mxnet.io/api/gluonts/gluonts.trainer.html#module-gluonts.trainer

To train longer you can play with the following, for example
* increase `learning_rate_decay_factor`: in case you set this to `1.0`, no reduction will occur and early stopping will not kick in
* increase `patience`: if you set this to a number larger than the number of epochs, again no reduction will occur and early stopping will not be able to kick in

Of course you can play with these values to slow down or accelerate learning rate reduction.

**Comment by k-user** [comment]
> 嘿@ k-user是的，这是由于学习率降低和提供的`Trainer`类中的提早停止逻辑所致。您可以在此处找到相关选项的文档：[https](https://gluon-ts.mxnet.io/api/gluonts/gluonts.trainer.html#module-gluonts.trainer) : [//gluon-ts.mxnet.io/api/gluonts/gluonts.trainer.html#module-gluonts.trainer](https://gluon-ts.mxnet.io/api/gluonts/gluonts.trainer.html#module-gluonts.trainer)
> 
> 要训​​练更长的时间，您可以玩以下游戏，例如
> 
> * 增加`learning_rate_decay_factor`：如果将其设置为`1.0`，则不会减少，并且不会提前停止
> * 增加`patience`：如果将其设置为大于历时数，则不会再出现减少，并且提早停止将无法进行
> 
> 当然，您可以使用这些值来减慢或加快学习速度的降低。



> Hey @k-user yes, this is due to learning rate reduction and early stopping logic in the provided `Trainer` class. You can find documentation to the related options here: https://gluon-ts.mxnet.io/api/gluonts/gluonts.trainer.html#module-gluonts.trainer
> 
> To train longer you can play with the following, for example
> 
> * increase `learning_rate_decay_factor`: in case you set this to `1.0`, no reduction will occur and early stopping will not kick in
> * increase `patience`: if you set this to a number larger than the number of epochs, again no reduction will occur and early stopping will not be able to kick in
> 
> Of course you can play with these values to slow down or accelerate learning rate reduction.

Thanks! I have edited the problem again, please kindly help to have a look.

**Comment by lostella** [comment]
@k-user can you open a separate issue? Use the bug report template, and if possible provide a minimal example that reproduces the issue

**Comment by k-user** [comment]
@lostella I think this issue  should be merged with #941,I will close it and reply in #941 .
