### ISSUE TITLE
How to select number of sample paths

### ISSUE THREAD

**Issue by mariosantosprivate** [awslabs/gluon-ts#1150]
Hi, so from my understanding and what I've found on previous issues related to this, when using:

```python
forecast_it, ts_it = make_evaluation_predictions(
    dataset=test_ds,
    predictor=deepAR_predictor,
    num_samples=100
)
```
The num_samples defines how many potential realizations of the future times series we'll generate, and therefore the more samples we choose, the more accurate the representation of the distribution is going to be. 

My question is, what is considered a suitable value for this and, does it depend on our data, and if so, how so?
In the extended tutorial a value of 100 is used, is there any reason for why this value was chosen?

**Comment by kaijennissen** [comment]
@mariosantosprivate While increasing the number of samples will increase the accuracy from a theoretical point of view, the benefit of more than 100 or 200 samples will only by small since the sample mean will converge to the true mean (Law of large numbers). 

See for example how the sample mean (picture below) of a standard normal distributed RV strongly varies at the beginning and then converges to the true mean of 0 with increasing sample size.

<img width="319" alt="grafik" src="https://user-images.githubusercontent.com/50238578/99073307-f8e50900-25b5-11eb-981a-25e512c83652.png">

```
import numpy as np
from matplotlib import pyplot as plt

x = np.random.randn(1000)
mu_hat = np.cumsum(x)/np.arange(1,1001)

plt.plot(mu_hat)
```

**Comment by mariosantosprivate** [comment]
Thank you!
