### ISSUE TITLE
Stuck at initiation with transformed training dataset

### ISSUE THREAD

**Issue by PeggyFan** [awslabs/gluon-ts#1246]
I followed the transformation steps in the [Extended Tutorial](https://gluon-ts.s3-accelerate.dualstack.amazonaws.com/master/examples/extended_forecasting_tutorial/extended_tutorial.html#2.-Transformation), specifically cell 29 through 35.

`train_tf` columns are:
```
['start',
 'source',
 'past_feat_dynamic_age',
 'future_feat_dynamic_age',
 'past_feat_dynamic_real',
 'future_feat_dynamic_real',
 'past_observed_values',
 'future_observed_values',
 'past_target',
 'future_target',
 'past_is_pad',
 'forecast_start']

past target shape: (269,)
future target shape: (30,)
past observed values shape: (269,)
future observed values shape: (30,)
past age feature shape: (269, 1)
future age feature shape: (30, 1)
```

and my estimator is:

```
estimator = DeepAREstimator(
    train_tf, #train_ds
    prediction_length=custom_ds_metadata['prediction_length'],
    context_length=context_length,
    freq=custom_ds_metadata['freq'],
    use_feat_dynamic_real=True,
    trainer=Trainer(ctx="cpu",
                    #ctx=mx.gpu(),
                    epochs=10,
                    num_batches_per_epoch=10
                   )
)
```

But when I called `predictor = estimator.train(train_tf)` it shows
```
learning rate from ``lr_scheduler`` has been overwritten by ``learning_rate`` in optimizer.
  0%|          | 0/10 [11:40<?, ?it/s]
```
and stuck there for a long time.

How can I start troubleshooting this?
(the estimator trains without issues with using the `train_ds`)

**Comment by lostella** [comment]
@PeggyFan the problem is the following: datasets (such as the one that you need to provide to `estimator.train`) are supposed to be iterable collections of dictionaries. In that notebook, `train_tf` is a generator, which means that once you have iterated it, the data is exhausted. This probably results in some endless loop during training.

In fact, I believe that that portion of the notebook, where `train_tf` is defined, is only meant to illustrate how transformations operate on datasets. But there is no need to manually apply the transformation that way, since the `estimator` object takes care of doing this when calling `estimator.train`: this is exactly what happens internally when you call `estimator.train(train_df)`.

Let me know if this is clear, I'm happy to help further.

**Comment by PeggyFan** [comment]
@lostella Thank you!
So it seems that the transformation is for customized estimator (if I were to build one from scratch), as using an estimator already available would automatically transform the dataset, am I correct?

**Comment by lostella** [comment]
Exactly, that's correct
