### ISSUE TITLE
Reduce the Conda dependencies listed in `env`

### ISSUE THREAD

**Issue by aalexandrov** [awslabs/gluon-ts#131]
Packages that are duplicated between a `requirements*.txt` and a `*.yml` file in `env` should be removed from the `*.yml` file.

**Comment by AaronSpieler** [comment]
The problem here is that Anaconda is not able to resolve the dependencies correctly if they are installed through pip, so we had to add some dependencies back.

See issue: https://github.com/awslabs/gluon-ts/pull/661
And issue: https://github.com/awslabs/gluon-ts/pull/658

And finally a potential solution: https://github.com/awslabs/gluon-ts/issues/662
