### ISSUE TITLE
Source code for "Deep Factors for Forecasting"(DEEP-FACTOR)

### ISSUE THREAD

**Issue by lennonmwy** [awslabs/gluon-ts#219]
## Description
- Hi, if there are source codes for paper "Deep Factors for Forecasting".  I want to implement the  DEEP FACTOR model mentioned in the pape for research purpose.

## References
- paper Deep Factors for Forecasting

**Comment by zhykoties** [comment]
Hello, do you want to discuss about the paper details by any chance?

**Comment by timoschowski** [comment]
Hi @lennonmwy, 

sorry for the delay in answering. We will bring the DeepFactor model to GluonTS in the near future (hopefully weeks rather than months) and @lovvge and @dcmaddix are eager to get their hands on it.

For the time being, we have the Deep State Space model implementation coming in now: https://github.com/awslabs/gluon-ts/pull/229

**Comment by tangyong** [comment]
Dear  Team,

Any progress on the issue( the DeepFactor model )?

Thanks!

**Comment by timoschowski** [comment]
There's a PR for this now: https://github.com/awslabs/gluon-ts/pull/259 

There's still some work needed, to make the data loader more efficient for example, so that it becomes usable.

**Comment by tangyong** [comment]
> There's a PR for this now: #259
> 
> There's still some work needed, to make the data loader more efficient for example, so that it becomes usable.

Thanks!
