### ISSUE TITLE
Documentation for Available Models is misleading

### ISSUE THREAD

**Issue by baniasbaabe** [awslabs/gluon-ts#2716]
## Description
In the official GluonTS Documentation, the „Available Models“ section is a bit misleading. I‘m unsure how the terms „univariate“ and „multivariate“ are used (since they are sometimes mixed with univariable and multivariable), but 

- Models like DeepAR or MQCNN are stated as Univariate, but can take multiple variables, while models like LSTNet are stated as multivariate, while they can‘t accept multiple variables.

## References

https://ts.gluon.ai/stable/getting_started/models.html

**Comment by lostella** [comment]
Hi @baniasbaabe, thanks for opening this. To clarify, "univariate" and "multivariate" refer to the target time series, the one being modeled: in the univariate case this is a sequence of scalars, hence a vector or 1D array, in the multivariate case this is a sequence of vectors, hence a 2D array.

Leaving this issue open since this should be made clear in the documentation.

**Comment by baniasbaabe** [comment]
Thanks, I already guessed it. It‘s like that that sometimes people are confused with univariate and univariable :). But it would be maybe a nice-to-have if we can add another column, if a model accepts multiple features or not. Or what do you say? :)
