### ISSUE TITLE
TSF datasets don't yield `feat_static_cat` which breaks `DeepState`

### ISSUE THREAD

**Issue by abdulfatir** [awslabs/gluon-ts#2804]
## Description
TSF datasets don't yield `feat_static_cat` for items in the dataset which breaks models that necessarily expect that field to be set, e.g., `DeepState`.

## To Reproduce

```python
from gluonts.dataset.repository.datasets import get_dataset

if __name__ == "__main__":
    dataset = get_dataset("kdd_cup_2018_without_missing")

    print(dataset.metadata.feat_static_cat) # [CategoricalFeatureInfo(name='feat_static_cat_0', cardinality='270')]
    print(next(iter(dataset.train)).keys()) # dict_keys(['target', 'start', 'item_id'])
```

**Comment by jaheba** [comment]
I guess we want to address two things:

* Add categorical feature to `TSF` datasets
* Add a check to `DeepState` that `feat_static_cat` is there?

**Comment by abdulfatir** [comment]
The first one, yes. The second one, I am not sure what the right way to do it is.

**Comment by kashif** [comment]
i would also appreciate a fix for this... in the mean time you can use the HF datasets https://huggingface.co/datasets/monash_tsf which has the cat feature

**Comment by huibinshen** [comment]
I am lacking a bit of the context here, and want to ask a few questions first.

Do we expect all the dataset in TSF, defined in `../datasets/repository/_tsf_datasets.py`, have `feat_static_cat` feature? If not, when do they have such feature and when do they won't? 

If we change `_tsf_datasets.py` so that `feat_static_cat` always exist, what side effect it may have on other model? We could achieve it by adding a function after this line https://github.com/awslabs/gluonts/blob/dev/src/gluonts/dataset/repository/_tsf_datasets.py#L260 .

If only several models such as `DeepState` expect `feat_static_cat`, would it be simpler to ensure that in the `DeepState` model for example by adding a check function? To me it would not impact other components and models.

Thoughts?

**Comment by kashif** [comment]
so in theory all time series in a particular dataset can have the trivial "cat" feature namely the id of the time series in the dataset. I believe all of the datasets have this... but not the monash-tst repository ones... so things break 

the deepAR model in the pytorch folder also can take static cat. features so it's not just Deepstate...

**Comment by kashif** [comment]
i believe the fix is to add the appropriate key and value of `[i]` here https://github.com/awslabs/gluonts/blob/dev/src/gluonts/dataset/repository/_tsf_datasets.py#LL209C19-L209C19 and https://github.com/awslabs/gluonts/blob/dev/src/gluonts/dataset/repository/_tsf_datasets.py#L219

**Comment by huibinshen** [comment]
> i believe the fix is to add the appropriate key and value of `[i]` here https://github.com/awslabs/gluonts/blob/dev/src/gluonts/dataset/repository/_tsf_datasets.py#LL209C19-L209C19 and https://github.com/awslabs/gluonts/blob/dev/src/gluonts/dataset/repository/_tsf_datasets.py#L219

Yeah, that's where the fix should be.
