### ISSUE TITLE
Theoretical: Improving DeepAR predictions?

### ISSUE THREAD

**Issue by andmib** [awslabs/gluon-ts#293]
I have a large set of related time series, some very sparse, and some not very sparse.

Using default parameters for the `DeepAR` estimator, even when training on 1 million+ series, for nearly all predictions (500 traces per time series from `make_evaluation_prediction`), the forecast tends to skew low, and is non-reactive. That is, the change from time point to time point on the forecast is small, whereas in the original data the changes are quite large. See links below, with monthly time series forecasting out 6 months (with a context length of 6).

![image](https://user-images.githubusercontent.com/12818070/64494112-c1aef580-d256-11e9-87e8-0a527ea132d6.png)
![image](https://user-images.githubusercontent.com/12818070/64494115-c70c4000-d256-11e9-87ba-2f7d30313bc2.png)

Does anybody have best-practices suggestions, specifically in the context of DeepAR, that would help improve the reactivity of the forecast from point-to-point?

**Comment by vafl** [comment]
For future reference, my guess is that missing values are represented as `0` in the target. They should instead be represented using `NaN`.

**Comment by andmib** [comment]
> For future reference, my guess is that missing values are represented as `0` in the target. They should instead be represented using `NaN`.

Thanks for the reply! Those center values are actually 0's. Each time series starts on a different date, but after the first sale, all of the subsequent values should be filled in with 0 (because my time series doesn't really have "missing values" per se - if there is no value, it's a 0-sale).

**Comment by andmib** [comment]
@vafl - I re-checked the structure of my data, and it looks correct. My data is technically in fiscal months, but I'm using month-end time stamps along with the `M` frequency. I am consistently getting lower-biased predictions across the board, even for stationary series. I realize this may not be the proper forum for this, but do you have any suggestions in terms of `GluonTS` `DeepAR` parameters? I've attached an example below (trained only on one series, 100 epochs, 20 batch size - but get a similar prediction if training on millions of series).

![image](https://user-images.githubusercontent.com/12818070/64616301-4f4f2a00-d3aa-11e9-9be7-39494f06d68e.png)

**Comment by rrgunukula** [comment]
@andmib I'm working on a similar problem and facing the same issue where my predictions are non reactive and are underpredicting. Have you been able to figure out the root cause of your problem. My data doesn't contain any missing values and is spiky in nature but max value of my predictions are less than 80th quantile of my training data which is something I don't understand at all. Thanks.

**Comment by geoalgo** [comment]
This issue seems related to https://github.com/awslabs/gluon-ts/issues/302. Since you have a count distribution, you could try negative binomial that should provide a better fit for your data (as Student-T cannot model count data very well even if you have many data to train). 

I see some -1 values, this seems weird for count data, did you encode missing values with '-1'? If this is case, it would be better to use 'NaN' as @vafl suggested.

**Comment by Alit10** [comment]
@andmib  @rrgunukula  Did you find a solution for this one ?

**Comment by rrgunukula** [comment]
Unfortunately I couldn't get it to work properly on my use case then and stopped using it
