### ISSUE TITLE
Use Gluon-TS for overlapping time series samples

### ISSUE THREAD

**Issue by erap129** [awslabs/gluon-ts#333]
Hello,  
From the ['Extended forecasting tutorial'](https://gluon-ts.mxnet.io/examples/extended_forecasting_tutorial/extended_tutorial.html) I infer that Gluon-TS can be used only for non-overlapping time-series samples.  This is because the 'test' portion of each data sample is always its last part, and if I have overlapping training samples it means my model will learn from the test data, which isn't good.  
Is there any recommended way to handle overlapping data samples with Gluon-TS?  
Thanks a lot

**Comment by mbohlkeschneider** [comment]
Hi @erap129,

thank you for your interest in GluonTS. I'm not sure I understand your issue. Can you provide a minimal example with some toy data?

**Comment by jaheba** [comment]
Hello @erap129,
yes, it is good practise to split the training and test-datasets into time-distinct parts. This is mainly for the reason of achieving good accuracy metrics. If a model is tested on data it already has some knowledge about, it will usually perform better than on independent data. The simple reason being that often time-series are related (think about a black-out on an electricity dataset).

That's why one wants to split the data on the time-axis to test the model on new, unseen values. There shouldn't really be much of an impact on the actual performance of the model on other new data.

So, in that regard: No, it's not true that you can not use GluonTS on overlapping time-series data.
