### ISSUE TITLE
DeepState error

### ISSUE THREAD

**Issue by antonkiselevtdg** [awslabs/gluon-ts#399]
## Description
Can't use DeepState

## To Reproduce

When I run

`from gluonts.model.deepstate import DeepStateEstimator`

I used
https://gluon-ts.mxnet.io/api/gluonts/gluonts.model.deepstate.html
as guidelines

## Error Message
I get the following error:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-a02fe352111a> in <module>
----> 1 from gluonts.model.deepstate import DeepStateEstimator

ModuleNotFoundError: No module named 'gluonts.model.deepstate'

**Comment by dai-ichiro** [comment]
What is your file name?
If the nema is inappropriate, you will get the error.

**Comment by jaheba** [comment]
Hi @antonkiselevtdg,

are you using the gluon-ts via `pip install gluonts`?

The problem is that our website currently reflects our master branch and not the latest release (see also #394). I believe that DeepState was added after v0.3.3.

You can checkout the current master branch and then use `pip install -e .` in the folder to install the latest version of gluon-ts.

Sorry for the inconvenience!

**Comment by antonkiselevtdg** [comment]
Hi jaheba,

Thank you very much for details.
