### ISSUE TITLE
DeepAR dynamic features = Covariates ? 

### ISSUE THREAD

**Issue by Math9999** [awslabs/gluon-ts#458]
(Please state your question in the title, and add here any relevant details,
like a description of the problem, code snippets, examples, and so on.)

**Dataset:**
SML2010: consists of weather related parameters (13 series) such as temperature, relative humidity, sunlight intensity collected from a monitor system mounted in a house. (https://archive.ics.uci.edu/ml/datasets/SML2010)

**Prediction:**
I would like to predict the temperature. Therefore I use temperature as the target time series and all other 12 series as covariates.

**Question A:**
Can I set the covariates as dynamic features in DeepAR ? Does that make sense?

**Question B:**
The time series are in a pandas dataframe. (https://github.com/awslabs/gluon-ts)

But how do I add one and in another example multiple dynamic features to one target series?
The following example for just one dynamic feature does not work.   
![image](https://user-images.githubusercontent.com/57505332/69007098-8b1de700-0939-11ea-9df9-3f50ed6e459f.png)

It would be great if you could help out.

All the best

**Comment by gjmulder** [comment]
Unlike static features, dynamic features need to be provided as part of the prediction. Unless you can independently obtain (or forecast) your additional covariates then I think your approach won't work. Even if you did forecast them, you have trained on the actual values of your covariates and not the forecasted values, which will likely cause problems with your model accuracy. GIGO.

You need to provide a 2D numpy array as feat_dynamic_real. Try using df.values.

**Comment by Math9999** [comment]
Thank you very much. Your explanation has clarified the situation.

**Comment by timoschowski** [comment]
A couple of more thoughts here: 
- if you don't have future values you can transform your original features into something else, which you could then more easily set (instead of using the direct value). For example, instead of using sunlight directly, you could use the co-variate "absolute/relative change to yesterday". This is a value that you can set more easily for the future often
- another approach is to use mulit-variate forecasting techniques where you forecast everything jointly
- or you pick a different model in which you may have some features for the past (e.g., to explain certain effects) but not in the future.
