### ISSUE TITLE
Speed up Forecast 

### ISSUE THREAD

**Issue by kaleming** [awslabs/gluon-ts#493]
Hi,

I am doing some tests on a dataset to predict the next seven days of 500,000 timeseries (around 200 days each).

After training the model, I have loaded the entire dataset into this 'ListDataset':

```
test_ds = ListDataset([{"start":a , "target":b}
                        for a, b in zip(dataset['date'], dataset['y']])],
                      freq='D')
```

Then I try to run the model in order to get 7 days of prediction lenght for each timeseries:

`forecasts = list(predictor.predict(test_ds, num_eval_samples=50))`

However it takes too long (I am still running on google colab - More than 4 hours until now).

I am running on cpu. Does it make much difference running on gpu ?

Is there any better approach to run a prediction for each timeseries of the entire dataset ?

Thank you

**Comment by mbohlkeschneider** [comment]
Hi @kaleming ,

thank you for using GluonTS. I'm not sure whether there is a lot you can do to speedup inference. 

One think I noted is that you use a `ListDataset` to load the data and also invoke `list` on the forecasts. 

You can use a `[FileDataset](https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/dataset/common.py#L188)` instead and just iterate for that to generate the forecasts. That will at least save you to load all the data into memory before during a forecast. 

Another thing you can do is to slice your data into batches and run this through to produce the forecasts. The data from batch can be parallelized. In this case, you can take advantage of a GPU. The GPU will not help much if you the forecasts individually.

**Comment by vafl** [comment]
In addition to the suggestions from @mbohlkeschneider, you can also try to parallelize the model using multiple cores. To do so, wrap the predictor in a `ParallelizedPredictor` and set the following environment variables before starting the prediction script.

```
OMP_NUM_THREADS=1
MXNET_ENGINE_TYPE=NaiveEngine
```

I'm not 100% sure whether this gives an improvement for the neural network models, since mxnet does some parallelization automatically inside the model. Let me know if this works.

**Comment by mbohlkeschneider** [comment]
@vafl suggestion is great. 

Another comment: If you say that you want to predict for 200 days, I assume that you set `prediction_length=200`? 

I just checked locally on electricity, and it takes ~18 minutes to predict and evaluate ~2000 time series with that `prediction_length=200` and `num_samples=100`. 

Thus, it would take (500000/2000)*18 = 45000 minutes (750 hours) to evaluate 500000 time series with that `prediction_length`. 

Since computation time during inference scales linearly with the `prediction_length`, it might be the most sensible thing to forecast less days. Otherwise, I would recommend splitting the dataset and evaluating on multiple machines.

**Comment by kaleming** [comment]
Hi,

First of all, thank you very much for both suggestions.

@mbohlkeschneide, when you mentioned to use FileDataset instead ListDataset, you mean:

1- First save my dataset into json format:
```
with open('path', 'w') as fp:
    dataset=( {"start":a , "target":b} for a, b in zip(dataset['date'], dataset['y']]))
    for i in dataset:
           ujson.dump(i, fp)
```
2- Load using 'FileDataset'

`data = FileDataset('path', freq="D")`

3- Run:

`list(predictor.predict(data, num_eval_samples=50))`

Is it correct this approach sequence ?

___________________________

>  So from my estimate, inference should take a bit over 4 hours to compute. I keep the post above for reference.

Yes you are correct. It took 4h30.

> you can also try to parallelize the model using multiple cores. To do so, wrap the predictor in a ParallelizedPredictor

Thank you @vafl, I will try to do this on google colab, and let you know if worked.

**Comment by mbohlkeschneider** [comment]
I think if you first have to dump the data to disk then there would be no benefit in using the `FileDataset` and this would not save time (probably cost even more). Seems that loading the data via `ListDataset` does not account for a lot of the computing time, so it seems that the impact is minor.

**Comment by Akaori** [comment]
Hi @mbohlkeschneider, 
Thank you again, I got your point.

My last question:

1- Is it possible to combine gluonts with dask?
I mean, load the json file with Dask Bag in order to have more control over the cluster and number workers / threads per worker.

**Comment by kaleming** [comment]
Ok. 
Maybe I can do this in order to save memory during the operation as you said.

Thank you again

**Comment by mbohlkeschneider** [comment]
Let us know what worked for you in the end! Closing this for now. Feel free to reopen if you have more questions.

**Comment by lotsoffood** [comment]
@kaleming Did you have any success speeding up inference through parallelization?
