### ISSUE TITLE
Distributional error metrics

### ISSUE THREAD

**Issue by alexhallam** [awslabs/gluon-ts#516]
I am looking for a way to calculate **pinball loss** or **rank probability score**. I show some of my output below. I am curious what the `QuantileLoss` is. Can I use that metric to get pinball loss? 

I set up some quantiles as follows:
```
# eval
quantile_seq = np.arange(0.1, 1 , .1)
evaluator = Evaluator(quantiles=quantile_seq)
agg_metrics, item_metrics = evaluator(iter(tss), iter(forecasts), num_series=len(test_ds))
print(json.dumps(agg_metrics, indent=4))
```

the output was

```
    "MSE": 5.173077055395188,
    "abs_error": 1937.2383211255074,
    "abs_target_sum": 1838.0,
    "abs_target_mean": 0.9771398192450824,
    "seasonal_error": 6.693360194745236,
    "MASE": 0.16621583137977658,
    "sMAPE": 1.9511674293834367,
    "MSIS": 5.1788325358267935,
    "QuantileLoss[0.1]": 656.3897180770059,
    "Coverage[0.1]": 0.10419989367357789,
    "QuantileLoss[0.2]": 1042.5795287945307,
    "Coverage[0.2]": 0.1339712918660287,
    "QuantileLoss[0.30000000000000004]": 1352.888840725538,
    "Coverage[0.30000000000000004]": 0.15683147262094635,
    "QuantileLoss[0.4]": 1630.0921277590678,
    "Coverage[0.4]": 0.25465178096757046,
    "QuantileLoss[0.5]": 1937.2383209627733,
    "Coverage[0.5]": 0.41626794258373206,
    "QuantileLoss[0.6]": 2267.2348443405704,
    "Coverage[0.6]": 0.5614035087719298,
    "QuantileLoss[0.7000000000000001]": 2560.9445986107776,
    "Coverage[0.7000000000000001]": 0.6177565124933547,
    "QuantileLoss[0.8]": 2764.1959102034393,
    "Coverage[0.8]": 0.6544391281233386,
    "QuantileLoss[0.9]": 2777.113136820318,
    "Coverage[0.9]": 0.6985645933014354,
    "RMSE": 2.274439943237717,
    "NRMSE": 2.327650453335226,
    "ND": 1.0539925577396667,
    "wQuantileLoss[0.1]": 0.3571217182138226,
    "wQuantileLoss[0.2]": 0.5672358698555662,
    "wQuantileLoss[0.30000000000000004]": 0.7360657457701513,
    "wQuantileLoss[0.4]": 0.8868836386066745,
    "wQuantileLoss[0.5]": 1.053992557651128,
    "wQuantileLoss[0.6]": 1.2335336476281666,
    "wQuantileLoss[0.7000000000000001]": 1.3933322081669084,
    "wQuantileLoss[0.8]": 1.503915076280435,
    "wQuantileLoss[0.9]": 1.5109429471274851,
    "mean_wQuantileLoss": 1.027002601033371,
    "MAE_Coverage": 0.10114596254947134
}
```

**Comment by jgasthaus** [comment]
Hi @alexhallam, 

the QuantileLoss here is the exactly the pinball loss, scaled by a factor of two (to make it agree with the absolute error for q=0.5), defined as:

https://github.com/awslabs/gluon-ts/blob/08ab434b1e0946c21010ddbb4248288f8f043599/src/gluonts/evaluation/_base.py#L346-L352

This is then summed over all evaluation time points and time series.

The ``wQuantileLoss[q]`` metrics are ``QuantileLoss[q]/abs_target_sum``, and ``mean_wQuantileLoss`` is the average of these scaled quantile losses, which gives you an approximation to CRPS.

**Comment by alexhallam** [comment]
Thanks! So if I divide the `QuantileLoss` by 2 I get pinball. How close is `mean_wQuantileLoss` to  CRPS? I am curious because I am comparing metrics against various other forecast methods and I would like them to have common ground.

**Comment by ColinLeverger** [comment]
Hi @alexhallam , did you learn more about your previous question :

> How close is mean_wQuantileLoss to CRPS?

I'm facing the same question now!

**Comment by alexhallam** [comment]
@ColinLeverger I ended up coding my own pinball loss function outside of this package and applied it to all the forecasting methods I was interested in. Pinball Loss is more common for the community I had to present to. Also it takes three short lines of code to write. Let me know if you need anything else.

**Comment by ColinLeverger** [comment]
Thank you @alexhallam for your answer! 
Then, the question still stands... Any thoughts, @jgasthaus ?

**Comment by Serendipity31** [comment]
## Explaining the relationship between Mean_wQuantileLoss and CRPS
@ColinLeverger and @alexhallam - It's been a while since you posed this question, but I think I have an answer for you. I don't suppose you're likely see this, but perhaps others will. [Berrisch and Ziel (2021)](https://arxiv.org/pdf/2102.00968.pdf), equation 9, shows how a mean of quantile losses can serve as an approximation to CRPS. I've taken a screenshot below and the full paper is attached: [Berrisch and Ziel (2021) CRPS Learning.pdf](https://github.com/awslabs/gluonts/files/13811294/Berrisch.and.Ziel.2021.CRPS.Learning.pdf)


![image](https://github.com/awslabs/gluonts/assets/10465394/5fb6d58b-38ca-43ae-bf74-92ae311ab52c)


As the text that follows on from equation 9 explains, this works if the quantile levels selected form an "equidistant dense grid". In the limit, as the gap between quantiles used shrinks, and the coverage expands to [0, 1], mean quantile loss converges to CRPS.

The default setting for `quantiles` in `Evaluator` provides an 'equidistant dense grid' because it's [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]. Each quantile is larger than the last and the gap between each is a constant 0.1. However, it's not an especially dense grid. In the paper, Berrisch and Ziel point out that the larger and denser the grid is that one uses, the closer mean quantile loss will be to CRPS. They suggest it's common when wanting to approximate CRPS in this way to use all the percentiles (i.e. [0.01, 0.02, ..., 0.99]). In theory, however, you could make an even denser grid - e.g. [0.001, 0.002, ... , 0.999] and it would be an even _closer_ approximation to CRPS. 

So I think that "how close" `Mean_wQuantileLoss` gets to CRPS is a function of how you set up the `quantiles` input to `Evaluator`.

**Comment by alexhallam** [comment]
Interesting.

As a side note that no one needs to know, there was a time when I was using Letter Values of the empirical distribution which is not equidistant at all, and pumping them into QL and pinball. But non-equidistant grids may not be what is needed sometimes.

**Comment by Serendipity31** [comment]
I didn't glean from the paper why the grids being equidistant was important, but if I had to guess I would say it has to do with the idea of taking a limit as that gap width goes to zero, which only really makes sense to think about if the gap width is the same across the whole grid. 

The part of your question I couldn't answer is how the weighting by `abs_target_sum` fits into things. I don't know why that's done. Is it just a kind of re-scaling that is necessary in the event that target series have very different scales from each other?

**Comment by IamginE** [comment]
> The part of your question I couldn't answer is how the weighting by `abs_target_sum` fits into things. I don't know why that's done. Is it just a kind of re-scaling that is necessary in the event that target series have very different scales from each other?

Maybe a bit late to the party, but I currently ran into the same question. Basically, dividing by `abs_target_sum` is a rescaling procedure that ensures that CRPS is often in the interval of [0,1] (although it can get larger than 1). However, from the papers I have read, this is actually not part of the CRPS definition, which you can think of as a generalization of the MAE (e.g., see here: https://towardsdatascience.com/crps-a-scoring-function-for-bayesian-machine-learning-models-dd55a7a337a8) that is scale-sensitive.
