### ISSUE TITLE
Extract Predicted Covariance Matrix from gpvar.GPVAREstimator & deepvar.DeepVAREstimator

### ISSUE THREAD

**Issue by StatMixedML** [awslabs/gluon-ts#605]
Hi,

Does the current implementation of gpvar.GPVAREstimator & deepvar.DeepVAREstimator allow to extract the predicted Covariance Matrix. I am asking because it is mentioned in the paper

[High-Dimensional Multivariate Forecasting with Low-Rank Gaussian Copula Processes](https://arxiv.org/pdf/1910.03002.pdf): **Figure 1: Top: covariance matrix predicted by our model.**

Would be really great to have that information available.

Thanks!

**Comment by mbohlkeschneider** [comment]
Hi @StatMixedML, 

you can get the covariance matrix using the code [here](https://github.com/mbohlkeschneider/gluon-ts/blob/mv_release/src/gluonts/multivariate/recover_artificial_paper.py#L78).

One note: There is no "the covariance matrix" because the covariance is estimated using the the current data context. Thus, every time you pass different data into the network the covariance matrix is estimated with respect to that data. You can also refer to the code above how to do that. 

Hope that helps.

**Comment by StatMixedML** [comment]
Thanks @mbohlkeschneider! Appreciate your help.

I close the issue now.

**Comment by yitao-yu** [comment]
Hi! @mbohlkeschneider 

I hope that you are here, sorry to bother you. 

The code seems to be a code for training, and it will unroll for context_length on future data, do you have codes for prediction? I tried with InferenceDataLoader and Predictor.prediction_net. It doesn't seem to work (It throws me a dim*num_samples ndarray, which I cannot comprehend and extract distr_args). I also tried with DistributionForecast. It also threw me an error.

**Comment by mbohlkeschneider** [comment]
I have not written code to do this during inference. Can you share a reproducible example?
