### ISSUE TITLE
finding state space parameters in Deepstate

### ISSUE THREAD

**Issue by parimuns** [awslabs/gluon-ts#610]
Hello 
How can we find the state space parameters like prior means ,smoothing parameter and observation noise using GLUONTS ? As these are calculated and shown in DeepState paper .
however,also how can we find noise_std bounds ,innovation bounds etc.to be used by DeepState Estimator

Can you please give any example of DeepState ?

**Comment by lostella** [comment]
@parimuns good point: the state space model parameters are not exposed currently, since the model samples from the process and returns a SampleForecast based on such samples. However, this is a bit of an artifact and we could instead return a DistributionForecast holding the original linear dynamical system object, with all the coefficients in it.

Turning this into an enhancement request, I'll try to get this done whenever possible. If you want to take a shot at it, feel free to assign it to yourself.

**Comment by parimuns** [comment]
Thanks a lot for your reply.In the "Deep State Space Models for Time Series Forecasting" paper,in Figure 3 authors have shown graphs of different state space parameters . Can you share some source code or reference that how those can be evaluated ?

**Comment by parimuns** [comment]
> @parimuns good point: the state space model parameters are not exposed currently, since the model samples from the process and returns a SampleForecast based on such samples. However, this is a bit of an artifact and we could instead return a DistributionForecast holding the original linear dynamical system object, with all the coefficients in it.
> 
> Turning this into an enhancement request, I'll try to get this done whenever possible. If you want to take a shot at it, feel free to assign it to yourself.

Thanks a lot for your reply.In the "Deep State Space Models for Time Series Forecasting" paper,in Figure 3 authors have shown graphs of different state space parameters . Can you share some source code or reference that how those can be evaluated ?

**Comment by lostella** [comment]
> Thanks a lot for your reply.In the "Deep State Space Models for Time Series Forecasting" paper,in Figure 3 authors have shown graphs of different state space parameters . Can you share some source code or reference that how those can be evaluated ?

@parimuns I cannot, until the change I mentioned above is implemented

**Comment by rshyamsundar** [comment]
> also how can we find noise_std bounds ,innovation bounds etc.to be used by DeepState Estimator

You can set these bounds depending on data by doing a hyper-parameter tuning. Lower bounds are not that critical and you can go with either 0 or the default 1e-6 (which avoids numerical issues). For upper bounds you can search for a suitable value in the range, e.g., [1e-3, 1.0]. 

Since time series is scaled (`scaling_normalization = True`), one need not go beyond 1.0 for the choosing the upper bound, irrespective of the magnitude of the time series.

**Comment by parimuns** [comment]
@rshyamsundar ...Congratulations on your novel work on deep-state space and thanks for sharing on gluonts.
Can you pls tell ,how to find the parameters which you have mentioned in your paper like prior means, smoothing parameter and observation noise? Is it possible through gluonts ?
