### ISSUE TITLE
The sample code cannot run

### ISSUE THREAD

**Issue by 1670811876** [awslabs/gluon-ts#611]
Hello.
When I ran the sample code in this Readme, there was always "MXNetError: vector::_M_range_insert
" errors.
![image](https://user-images.githubusercontent.com/44566000/74143640-20c5cb80-4c36-11ea-8de4-bfe9c85e6fa4.png)

**Comment by lostella** [comment]
@1670811876 can you add a few details about your setup? What version of gluonts and mxnet are you using?

**Comment by thatdanghill** [comment]
I saw this error as well on Ubuntu when trying to iterate through forecasts for a DeepAR model. 
My gluonts version was 0.4.2 and mxnet was 1.5.1.post0.
I patched it by rolling back mxnet from 1.5.1.post0 to 1.4.1 and pyarrow from 0.16.0 to 0.10.0. 

I ran the same code on my macOS without any errors. My hunch is that the difference is my Linux machine has a GPU and has CUDA installed, although the models aren't using the GPU (I see INFO:root:Using CPU).

**Comment by lostella** [comment]
The problem is with mxnet-1.5.x I believe: there is a bug there that prevents sampling operators from working correctly on Linux, see https://github.com/apache/incubator-mxnet/issues/16135

We look forward to mxnet-1.6 being released to solve issue. For now, I think sticking with mxnet-1.4.1 is the solution.
