### ISSUE TITLE
Can someone share how you are converting your normal tabular time-series data into required format.

### ISSUE THREAD

**Issue by rt3722** [awslabs/gluon-ts#649]
(Please state your question in the title, and add here any relevant details,
like a description of the problem, code snippets, examples, and so on.)

**Comment by rt3722** [comment]
I was going thorough extended forecasting tutorial but i could not see such example.

**Comment by jaheba** [comment]
Can you be more specific?

You could look at this script, where we take the M4-competition's csv files and convert them: https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/dataset/repository/_m4.py

The DeepAR documentation can also help, since in GluonTS we more or less reuse the json-lines format of DeepAR: https://docs.aws.amazon.com/sagemaker/latest/dg/deepar.html#deepar-inputoutput

**Comment by rt3722** [comment]
Thank you, the first link kind helps.
