### ISSUE TITLE
Remove hardcoded noise scale from CDFtoGaussianTransform 

### ISSUE THREAD

**Issue by jaschau** [awslabs/gluon-ts#669]
## Description
The CDFtoGaussianTransform used in gpvar and deepvar currently uses noise with a hard-coded scale of 0.2 as a regularizer for computation of the interpolated, empirical CDF.
This makes the CDFtoGaussianTransform unusable for any data which varies on a numerical scale << 0.2. 
This is highly unexpected for the user and should either be removed completely or documented very clearly in the documentation of both gpvar and deepvar.

**Comment by mbohlkeschneider** [comment]
Hi @jaschau, 

thank you for raising this issue. I agree that this could be configurable. Do you want to submit a pull request for that? 

I would like to clarify the current code. The 0.2 scale gets multiplied with the standard deviation of the data when computing the noise scale (as implemented [here](https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/transform/convert.py#L542)). Thus, the 0.2 scale should be usable regardless the scale of the data. In other words, the spread of the noise will be proportional to the spread in the data. Thus, if you are experiencing issues with these models, I suspect it has a different root cause.

**Comment by jaschau** [comment]
Hi @mbohlkeschneider,

thanks a lot for the quick response and the clarification of the code.

I indeed overlooked the multiplication by the std. Just for my understanding, is the std computed over the conditioning length or the context length?

As you correctly suspected, I was indeed puzzled by gpvar not performing well on my dataset when use_marginal_transformation=True and scaling=False. In fact, the behaviour was very similar to deepar with scaling=False which in my experience collapses to an essentially static noise scale with an inappropriate scale. Since my data was varying on a scale of ~ 0.1, I suspected the mentioned code to be the culprit. Sorry for the noise! 

Since I suspect that the precise value does not really matter when the noise scale is essentially given by the std, I will close the issue.

**Comment by mbohlkeschneider** [comment]
Hi @jaschau,

> I indeed overlooked the multiplication by the std. Just for my understanding, is the std computed over the conditioning length or the context length?

It is computed over the `conditioning_length` (or `history_length`, whatever is smaller). 

If you need more help on getting the model to work, feel free to open another issue.
