### ISSUE TITLE
Prediction index is wrong with weekly frequency

### ISSUE THREAD

**Issue by mbataillou** [awslabs/gluon-ts#750]
## Description
Gluon-ts uses pandas' date_range function to create an index this will change the start day and shift the following ones.

## To Reproduce

```python
import numpy as np

from gluonts.dataset.common import ListDataset
from gluonts.distribution import MultivariateGaussianOutput
from gluonts.model.deepar import DeepAREstimator
from gluonts.trainer import Trainer
from gluonts.evaluation.backtest import make_evaluation_predictions


train_dataset = ListDataset(
    data_iter=[
        {
            "start": "2019-01-01 00:00:00",
            "target": np.ones(shape=(4, 4)),
        },
    ],
    freq="W",
    one_dim_target=False,
)

test_dataset = ListDataset(
    data_iter=[
        {
            "start": "2019-01-01 00:00:00",
            "target": np.ones(shape=(4, 5)),
        },
    ],
    freq="W",
    one_dim_target=False,
)

estimator = DeepAREstimator(
    'W', prediction_length=1, trainer=Trainer(epochs=3, hybridize=False),
    distr_output=MultivariateGaussianOutput(dim=4),
)

predictor = estimator.train(train_dataset)

forecast_it, ts_it = make_evaluation_predictions(dataset=test_dataset, predictor=predictor, num_samples=10)

forecast_list = list(forecast_it)
ts_list = list(ts_it)
```

## Error message or code output
Where ts_list starts on the first sunday it found: '2019-01-06' instead of the provided start date: '2019-01-01'

```
DatetimeIndex(['2019-01-06', '2019-01-13', '2019-01-20', '2019-01-27',
               '2019-02-03'],
              dtype='datetime64[ns]', freq='W-SUN')
```

## Environment
- Operating system: Amazon Linux
- Python version: 3.6
- GluonTS version: a5539612 internal

**Comment by vafl** [comment]
Gluonts aligns time stamps to the pandas frequency. Since "W" is short for "W-SUN", all time stamps in the dataset are aligned to sundays.  We can relatively easily include support for [other pandas frequencies](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases) such as "W-TUE", which would be weekly time series with time stamps falling on tuesdays.

What we cannot easily support are a dataset with weekly time series where each series can start on a different day, because the feature processing relies on global time stamps that all time series align with.

Would the inclusion of additional frequencies like "W-TUE" solve your problem?

**Comment by mbataillou** [comment]
Hi,

The inclusion of additional frequencies would definitely help as one can have more control. However, this feature should also be supported by the estimator as the DeepAREstimator is the one complaining about 'W-MON' for example.

On the other hand we loose important information on the time features side as repeating weekly on a Wednesday shouldn't be the same as repeating every week on a Sunday (or at 1pm vs 8am).

We can still add those as static features but it seems like a hack. Do you think there is a better way to keep this information?

Thanks a lot !

**Comment by jaheba** [comment]
I think there is a mismatch between how we understand frequencies and how you want to use them.

We generally use them as aggregates, in the sense that, for example, we sum up all electricity consumption over a week. We then align any time-stamp of a week to the same representative datetime-value.

I assume your use-case is different, and you have events which occur once a week (rather than being the accumulation of that week), and thus the day-information matters.

When adding time-features, we don't add information about finer granularities. (E.g. for monthly frequency we use the month and the year, but not the day).

> We can still add those as static features but it seems like a hack. Do you think there is a better way to keep this information?

Yes, and no. I think the time features we add are also only static features, so there is no real difference here. I certainly see that there could be a way to enable finer granularities when adding time-features, re-using existing code.

**Comment by parthbkgadoya** [comment]
Is there any update related to supporting weekly frequency for any day of the week instead of default Sunday week frequency?
