### ISSUE TITLE
Investigate build process on Windows

### ISSUE THREAD

**Issue by lostella** [awslabs/gluon-ts#85]
The package build seems to be failing on Windows, apparently once again due to some hard-coded path.

Context is in #75

**Comment by jgasthaus** [comment]
This looks problematic:

https://github.com/awslabs/gluon-ts/blob/d7e73ec52cb49a52175e51e50ac1f30ed00f774c/setup.py#L43-L50

Also not sure whether this will behave correctly (since it has a "/" in the glob expression):

https://github.com/awslabs/gluon-ts/blob/d7e73ec52cb49a52175e51e50ac1f30ed00f774c/setup.py#L132

**Comment by dai-ichiro** [comment]
I made some modifications to 'setup.py', and I can install gluonts from source code on Windows.
- before
```
GPU_SUPPORT = 0 == int(
    subprocess.call(
        "nvidia-smi",
        shell=True,
        stdout=open("/dev/null", "w"),
        stderr=open("/dev/null", "w"),
    )
)
```
- after
```
import os

GPU_SUPPORT = 0 == int(
    subprocess.call(
        "nvidia-smi",
        shell=True,
        stdout=open(os.devnull, "w"),
        stderr=open(os.devnull, "w"),
    )
) 
```
