### ISSUE TITLE
Add lagged features

### ISSUE THREAD

**Issue by gmcaixeta** [awslabs/gluon-ts#922]
Hello,

I would like to know if there is some feature function on gluonts which can be used to include recursive lagged rolling mean into DeepAR estimator ? Something like `lags_seq` parameters ?

**Comment by benidis** [comment]
We have recently added a transformation that does as a special case what you describe:

https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/transform/feature.py#L433

The idea of the above transformation is to aggregate past windows and use these values as lags. You can define how to aggregate (e.g., mean, sum, etc.), the frequency of aggregation (e.g., hourly, daily, 5min, etc.), if the aggregation should be in calendar dates or in a rolling window fashion, and which aggregate lags you want to include (e.g., lag =[7] with mean daily aggregation of an hourly time series would include the mean value of the day one week ago, either by calendar or by exact time (aggregates a window 12 hours before and after the exact time one week ago)).

Of course you can chain many of these transformations with different aggregations if it is useful for your application. You can also set the aggregation frequency to 1 which essentially adds normal lags. 

This is not part of the default code of the DeepAR estimator transformation chain but it can be added manually for each use case.

**Comment by gmcaixeta** [comment]
Hi @benidis, thanks for your reply.
I am trying to learn from this [kaggle solution](https://www.kaggle.com/c/m5-forecasting-accuracy/discussion/164374). And I noticed that he created recursive rolling mean from target value.

I am trying to use this class you have created, but I am not sure I am doing it right.

```
from gluonts.dataset.artificial import ComplexSeasonalTimeSeries
from gluonts.transform.feature import AddAggregateLags


prediction_length = 5
dataset_length_min = 30 
dataset_length_max = dataset_length_min + 1

artificial_dataset = ComplexSeasonalTimeSeries(
    num_series=1,
    prediction_length=prediction_length,
    freq_str="D",
    length_low=dataset_length_min,
    length_high=dataset_length_max,
    min_val=0,
    max_val=2000,
)

train = ListDataset(artificial_dataset.train, freq="D")
test = ListDataset(artificial_dataset.test, freq="D")

rolling_mean_lag = AddAggregateLags(target_field='target', output_field='output', pred_length=5, base_freq='1 day',  agg_freq='1 day', agg_lags=[7])

[rolling_mean_lag.map_transform(i, is_train=True) for i in train]

AssertionError                            Traceback (most recent call last)

<ipython-input-102-86a7b68cd04b> in <module>()
----> 1 [rolling_mean_lag.map_transform(i, is_train=True) for i in train]

1 frames

/usr/local/lib/python3.6/dist-packages/gluonts/transform/feature.py in map_transform(self, data, is_train)
    515 
    516     def map_transform(self, data: DataEntry, is_train: bool) -> DataEntry:
--> 517         assert self.base_freq == data["start"].freq
    518 
    519         # convert to pandas Series for easier indexing and aggregation

AssertionError: 

```

He also modified the baseline network to predict more than 1 day with rolling predictions in the training phase, using Tweedie Loss. I noticed that you have a pull request related to `rolling predictions`. Is it related to this same methodology you are proposing here ( #831) ?

Thank you very much.

**Comment by benidis** [comment]
Try the following:

```
rolling_mean_lag = AddAggregateLags(
        target_field='target', 
        output_field='output', 
        pred_length=5, 
        base_freq='1D',  
        agg_freq='1D', 
        agg_lags=[7]
)
```
Basically, you have defined the frequencies in different format than in the dataset so it fails. With this fix your example works. Also note that with the above code there is no aggregation since the `agg_freq` is the same as the `base_freq` so the original lag values are used. 

>He also modified the baseline network to predict more than 1 day with rolling predictions in the training phase
I am not sure what he mean there exactly because DeepAR predicts as many time steps as defined by the `prediction_length` parameter in a recursive way.  Unless he means that he converted DeepAR to a seq2seq model and at time step $t$ you predict an horizon $t+1:t+h$ directly which does not seem the case.

Although I have not followed closely #831 I think the idea is a bit different and it has to do with manipulation of the dataset and not the model. A rough explanation of what this is doing is the following: assume you have daily data and a model that has a `prediction_length=7`, i.e., you predict the next week. For training usually we cut the last `prediction_length` window of the dataset so we can evaluate our model on it, i.e., `train_ds = data[:, :-7]`. During inference we basically predict the last window and we compare the predictions to the true values to see how well our model performs.

Now, what if you want to evaluate your model in a window larger than the one that is defined by the prediction horizon of your model? In this case, assume you want to evaluate your model on the last 3 weeks and not only on the last one in order to get a more accurate estimate of your model performance. Your model however can predict only 7 and not 21 days. What you can do in this case is to replicate your data. In particular, you can replicate each time series and cut it in different time steps, e.g., `data[:,:-21], data[:,:-14], data[:,:-7]` etc. The model is not aware that this is the same time series and it will just predict the next 7 days of each one of the above, which corresponds to predicting 3 weeks instead of 1. These cuts can be done in any way you want but the more fancy you get the bigger the overhead is in memory and of course the less data you have for training.

**Comment by gmcaixeta** [comment]
> `Also note that with the above code there is no aggregation since the agg_freq is the same as the base_freq so the original lag values are used.`

Thank you @benidis, it worked. I noticed that. 

> Assume you want to evaluate your model on the last 3 weeks and not only on the last one in order to get a more accurate estimate of your model performance. Your model however can predict only 7 and not 21 days. What you can do in this case is to replicate your data. In particular, you can replicate each time series and cut it in different time steps, e.g., data[:,:-21], data[:,:-14], data[:,:-7] etc. The model is not aware that this is the same time series and it will just predict the next 7 days of each one of the above, which corresponds to predicting 3 weeks instead of 1. These cuts can be done in any way you want but the more fancy you get the bigger the overhead is in memory and of course the less data you have for training.

Oh I see, now it's clear to me the difference.
Thank you for the explanation.

**Comment by benidis** [comment]
I am closing the issue. Feel free to reopen or create a new one in case you have more questions.
