### ISSUE TITLE
Discrepency for GluonTS between release version 0.5.0 and 0.4.2

### ISSUE THREAD

**Issue by wandersun** [awslabs/gluon-ts#947]
I used `DeepState` model in GluonTS. In 0.4.2, when I do inference,  I can attach new arrays for field `feat_dynamic_real` through iterating the `ListDataset` in a for loop, e.g.:

```
  def predict(self) -> IteratorForecast:
        for data_entry in self.train_dataset:
            linear_dynamic_trend = np.asarray(range(len(data_entry['target'] + self.predict_len))
            data_entry['feat_dynamic_real'] = get_dynamic_features(linear_dynamic_trend)
        return self.model.predict(self.train_dataset)
```

However, I am not able to assign values for `feat_dynamic_real`  field in this way in 0.5.0. The assigned `linear_dynamic_trend`, which is a numpy.ndarray will be ignored for unknown reasons.

Please help or at least mark this as known issue.

**Comment by lostella** [comment]
@wandersun thanks for reporting this. Could you come up with a minimal code snippet that we can copy-paste to reproduce the error?

In any case: I've never added fields to a dataset this way, but since you have a ListDataset constructed somewhere, my suggestion would be to just add the fields when the dataset is constructed. Why would that not be possible?
